def my_function():
    print("     "+"*" * 1)
    print("    "+"*" * 2)
    print("    "+"*" * 3)
    print("    "+"*" * 4)
    print("   "+"*" * 5)
    print("   "+"*" * 6)
    print("   "+"*" * 8)
    print("    "+"*" * 8)
    print("   "+"*" * 9)
    print("  "+"*" * 10)
    print(" "+"*" * 11)
    print("     "+"*" * 2)
    print("     "+"*" * 2)
    print("     "+"*" * 2)
    print("     "+"*" * 2)
    print("It is a bit windy!")

my_function()